language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - master

git:
  depth: 3

install:
  - make install

script:
  - make vet
  - make fmt-check
  - make embedmd
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2c4879f6307e970b85f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
